# config/_default/hugo.toml
baseURL = "https://brandmine-presskit.pages.dev"
languageCode = "en"
defaultContentLanguage = "en"
title = "Brandmine Press Kit Service"

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
  [languages.ru]
    weight = 2
    languageName = "Русский"
  [languages.zh]
    weight = 3
    languageName = "中文"
  [languages.ar]
    weight = 4
    languageName = "العربية"
    languagedirection = "rtl"

[params]
  description = "Professional press kits for Russian SME brands"
  
[taxonomies]
  tier = "tiers"
  sector = "sectors"